version: "3"
services:
  db:
    image: postgres:14
    container_name: geonames_db
    user: postgres
    # env_file:
    #   - app/config.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - todo_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "default"]
      #test: ["CMD-SHELL", "pg_isready -U admin -d default"]
        

  backend:
    image: example/database
    container_name: backend-dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8007:8007
    networks:
      - todo_net      

  


volumes:
  postgres:
networks:
    todo_net:




    